# Generated by Django 4.2.6 on 2023-10-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('dob', models.CharField(max_length=250)),
                ('age', models.CharField(max_length=5)),
                ('gender', models.CharField(max_length=250)),
                ('phn', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('address', models.TextField(blank=True)),
                ('department', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('materials', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Details',
            },
        ),
    ]
